version: "3.8"
services:
  server:
    container_name: server-mail-server
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT}:${PORT}"
    command: ["/app/main"]
